# Generated by Django 3.1.7 on 2021-03-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wudya', '0003_auto_20210305_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='other',
            field=models.ManyToManyField(through='wudya.OptionPair', to='wudya.Option'),
        ),
    ]
