# Generated by Django 3.1.7 on 2021-03-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wudya', '0005_auto_20210305_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='other',
            field=models.ManyToManyField(through='wudya.OptionPair', to='wudya.Option'),
        ),
    ]
