# Generated by Django 3.1.7 on 2021-03-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wudya', '0006_auto_20210305_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='other',
            field=models.ManyToManyField(related_name='_option_other_+', through='wudya.OptionPair', to='wudya.Option'),
        ),
    ]
