# Generated by Django 3.1.7 on 2021-03-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wudya', '0007_auto_20210305_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionpair',
            name='desc',
            field=models.CharField(default='placeholder', max_length=120),
            preserve_default=False,
        ),
    ]
