# Generated by Django 3.1.7 on 2021-03-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wudya', '0008_optionpair_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='other',
        ),
        migrations.RemoveField(
            model_name='option',
            name='votes_total',
        ),
    ]
